<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="4"
            failures="1"
            tests="3">

  <testsuite name="wallTest"
    errors="4" failures="1" hostname="" id="" package="wallTest" skipped="0"
    tests="3" time="37.81" timestamp="">
  
    <testcase name="sign in" classname="wallTest" time="10.49" assertions="1">

    
    </testcase>
  
    <testcase name="search" classname="wallTest" time="8.433" assertions="4">

    

    

    

    
    </testcase>
  
    <testcase name="saved articles" classname="wallTest" time="18.89" assertions="3">

    

      <failure message="Timed out while waiting for element &lt;[class=&#34;content-wrapper&#34;]&gt; to be present for 5000 milliseconds. - expected [0;32m&#34;visible&#34;[0m but got: [0;31m&#34;not found&#34;[0m">    at Page.savedArticles (/Users/Josephstone/DevMountain/WallStreetJournal/pageObjects/poopy.js:67:14)
    at Object.saved articles (/Users/Josephstone/DevMountain/WallStreetJournal/tests/wallTest.js:31:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

    <failure message="    at Page.savedArticles (/Users/Josephstone/DevMountain/WallStreetJournal/pageObjects/poopy.js:67:14)">    at Object.saved articles (/Users/Josephstone/DevMountain/WallStreetJournal/tests/wallTest.js:31:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>
    </testcase>
  

  

  
  </testsuite>
</testsuites>
